# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ClientInfo(object):
    def setupUi(self, ClientInfo):
        ClientInfo.setObjectName(_fromUtf8("ClientInfo"))
        ClientInfo.resize(701, 611)
        self.centralwidget = QtGui.QWidget(ClientInfo)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.docInfoBox = QtGui.QGroupBox(self.centralwidget)
        self.docInfoBox.setGeometry(QtCore.QRect(240, 30, 221, 141))
        self.docInfoBox.setObjectName(_fromUtf8("docInfoBox"))
        self.docNumber = QtGui.QLineEdit(self.docInfoBox)
        self.docNumber.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.docNumber.setReadOnly(True)
        self.docNumber.setObjectName(_fromUtf8("docNumber"))
        self.label_9 = QtGui.QLabel(self.docInfoBox)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_7 = QtGui.QLabel(self.docInfoBox)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.docSerial = QtGui.QLineEdit(self.docInfoBox)
        self.docSerial.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.docSerial.setReadOnly(True)
        self.docSerial.setObjectName(_fromUtf8("docSerial"))
        self.docType = QtGui.QLineEdit(self.docInfoBox)
        self.docType.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.docType.setReadOnly(True)
        self.docType.setObjectName(_fromUtf8("docType"))
        self.label_8 = QtGui.QLabel(self.docInfoBox)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_16 = QtGui.QLabel(self.docInfoBox)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.docDate = QtGui.QDateEdit(self.docInfoBox)
        self.docDate.setGeometry(QtCore.QRect(100, 110, 113, 22))
        self.docDate.setStyleSheet(_fromUtf8(""))
        self.docDate.setFrame(True)
        self.docDate.setReadOnly(True)
        self.docDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.docDate.setKeyboardTracking(True)
        self.docDate.setCalendarPopup(False)
        self.docDate.setObjectName(_fromUtf8("docDate"))
        self.mainInfoBox = QtGui.QGroupBox(self.centralwidget)
        self.mainInfoBox.setGeometry(QtCore.QRect(10, 10, 221, 171))
        self.mainInfoBox.setObjectName(_fromUtf8("mainInfoBox"))
        self.sex = QtGui.QLineEdit(self.mainInfoBox)
        self.sex.setGeometry(QtCore.QRect(100, 110, 113, 20))
        self.sex.setReadOnly(True)
        self.sex.setObjectName(_fromUtf8("sex"))
        self.label_3 = QtGui.QLabel(self.mainInfoBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.mainInfoBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.patrName = QtGui.QLineEdit(self.mainInfoBox)
        self.patrName.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.patrName.setReadOnly(True)
        self.patrName.setObjectName(_fromUtf8("patrName"))
        self.label = QtGui.QLabel(self.mainInfoBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.firstName = QtGui.QLineEdit(self.mainInfoBox)
        self.firstName.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.firstName.setReadOnly(True)
        self.firstName.setObjectName(_fromUtf8("firstName"))
        self.label_4 = QtGui.QLabel(self.mainInfoBox)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lastName = QtGui.QLineEdit(self.mainInfoBox)
        self.lastName.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.lastName.setReadOnly(True)
        self.lastName.setObjectName(_fromUtf8("lastName"))
        self.birthDate = QtGui.QDateEdit(self.mainInfoBox)
        self.birthDate.setGeometry(QtCore.QRect(100, 140, 113, 22))
        self.birthDate.setStyleSheet(_fromUtf8(""))
        self.birthDate.setFrame(True)
        self.birthDate.setReadOnly(True)
        self.birthDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.birthDate.setKeyboardTracking(True)
        self.birthDate.setCalendarPopup(False)
        self.birthDate.setObjectName(_fromUtf8("birthDate"))
        self.label_13 = QtGui.QLabel(self.mainInfoBox)
        self.label_13.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.omcInfoBox = QtGui.QGroupBox(self.centralwidget)
        self.omcInfoBox.setGeometry(QtCore.QRect(470, 10, 221, 171))
        self.omcInfoBox.setObjectName(_fromUtf8("omcInfoBox"))
        self.omcNumber = QtGui.QLineEdit(self.omcInfoBox)
        self.omcNumber.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.omcNumber.setReadOnly(True)
        self.omcNumber.setObjectName(_fromUtf8("omcNumber"))
        self.label_10 = QtGui.QLabel(self.omcInfoBox)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.omcInfoBox)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.omcSerial = QtGui.QLineEdit(self.omcInfoBox)
        self.omcSerial.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.omcSerial.setReadOnly(True)
        self.omcSerial.setObjectName(_fromUtf8("omcSerial"))
        self.omcKind = QtGui.QLineEdit(self.omcInfoBox)
        self.omcKind.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.omcKind.setReadOnly(True)
        self.omcKind.setObjectName(_fromUtf8("omcKind"))
        self.label_12 = QtGui.QLabel(self.omcInfoBox)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.omcBegDate = QtGui.QDateEdit(self.omcInfoBox)
        self.omcBegDate.setGeometry(QtCore.QRect(100, 110, 113, 22))
        self.omcBegDate.setStyleSheet(_fromUtf8(""))
        self.omcBegDate.setFrame(True)
        self.omcBegDate.setReadOnly(True)
        self.omcBegDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.omcBegDate.setKeyboardTracking(True)
        self.omcBegDate.setCalendarPopup(False)
        self.omcBegDate.setObjectName(_fromUtf8("omcBegDate"))
        self.label_14 = QtGui.QLabel(self.omcInfoBox)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.omcEndDate = QtGui.QDateEdit(self.omcInfoBox)
        self.omcEndDate.setGeometry(QtCore.QRect(100, 140, 113, 22))
        self.omcEndDate.setStyleSheet(_fromUtf8(""))
        self.omcEndDate.setFrame(True)
        self.omcEndDate.setReadOnly(True)
        self.omcEndDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.omcEndDate.setKeyboardTracking(True)
        self.omcEndDate.setCalendarPopup(False)
        self.omcEndDate.setObjectName(_fromUtf8("omcEndDate"))
        self.label_15 = QtGui.QLabel(self.omcInfoBox)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 91, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.mainBox = QtGui.QGroupBox(self.centralwidget)
        self.mainBox.setGeometry(QtCore.QRect(200, 190, 291, 61))
        self.mainBox.setTitle(_fromUtf8(""))
        self.mainBox.setObjectName(_fromUtf8("mainBox"))
        self.start_button = QtGui.QPushButton(self.mainBox)
        self.start_button.setGeometry(QtCore.QRect(70, 30, 161, 23))
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.lineEdit = QtGui.QLineEdit(self.mainBox)
        self.lineEdit.setGeometry(QtCore.QRect(120, 10, 61, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_6 = QtGui.QLabel(self.mainBox)
        self.label_6.setGeometry(QtCore.QRect(100, 10, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.searchBox = QtGui.QGroupBox(self.centralwidget)
        self.searchBox.setGeometry(QtCore.QRect(10, 250, 671, 321))
        self.searchBox.setObjectName(_fromUtf8("searchBox"))
        self.searchLastName = QtGui.QLineEdit(self.searchBox)
        self.searchLastName.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.searchLastName.setReadOnly(False)
        self.searchLastName.setObjectName(_fromUtf8("searchLastName"))
        self.label_5 = QtGui.QLabel(self.searchBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_17 = QtGui.QLabel(self.searchBox)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.searchFirstName = QtGui.QLineEdit(self.searchBox)
        self.searchFirstName.setGeometry(QtCore.QRect(110, 50, 113, 20))
        self.searchFirstName.setReadOnly(False)
        self.searchFirstName.setObjectName(_fromUtf8("searchFirstName"))
        self.label_18 = QtGui.QLabel(self.searchBox)
        self.label_18.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.searchPatrName = QtGui.QLineEdit(self.searchBox)
        self.searchPatrName.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.searchPatrName.setReadOnly(False)
        self.searchPatrName.setObjectName(_fromUtf8("searchPatrName"))
        self.searchDocSerial = QtGui.QLineEdit(self.searchBox)
        self.searchDocSerial.setGeometry(QtCore.QRect(110, 110, 113, 20))
        self.searchDocSerial.setReadOnly(False)
        self.searchDocSerial.setObjectName(_fromUtf8("searchDocSerial"))
        self.label_19 = QtGui.QLabel(self.searchBox)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.searchDocNumber = QtGui.QLineEdit(self.searchBox)
        self.searchDocNumber.setGeometry(QtCore.QRect(110, 140, 113, 20))
        self.searchDocNumber.setReadOnly(False)
        self.searchDocNumber.setObjectName(_fromUtf8("searchDocNumber"))
        self.label_20 = QtGui.QLabel(self.searchBox)
        self.label_20.setGeometry(QtCore.QRect(10, 140, 91, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.searchDocType = QtGui.QLineEdit(self.searchBox)
        self.searchDocType.setGeometry(QtCore.QRect(110, 170, 113, 20))
        self.searchDocType.setReadOnly(False)
        self.searchDocType.setObjectName(_fromUtf8("searchDocType"))
        self.label_21 = QtGui.QLabel(self.searchBox)
        self.label_21.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.searchBox)
        self.label_22.setGeometry(QtCore.QRect(10, 230, 91, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.searchOmcType = QtGui.QLineEdit(self.searchBox)
        self.searchOmcType.setGeometry(QtCore.QRect(110, 260, 113, 20))
        self.searchOmcType.setReadOnly(False)
        self.searchOmcType.setObjectName(_fromUtf8("searchOmcType"))
        self.searchOmcSerial = QtGui.QLineEdit(self.searchBox)
        self.searchOmcSerial.setGeometry(QtCore.QRect(110, 200, 113, 20))
        self.searchOmcSerial.setReadOnly(False)
        self.searchOmcSerial.setObjectName(_fromUtf8("searchOmcSerial"))
        self.label_23 = QtGui.QLabel(self.searchBox)
        self.label_23.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.searchBox)
        self.label_24.setGeometry(QtCore.QRect(10, 260, 91, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.searchOmcNumber = QtGui.QLineEdit(self.searchBox)
        self.searchOmcNumber.setGeometry(QtCore.QRect(110, 230, 113, 20))
        self.searchOmcNumber.setReadOnly(False)
        self.searchOmcNumber.setObjectName(_fromUtf8("searchOmcNumber"))
        self.search_button = QtGui.QPushButton(self.searchBox)
        self.search_button.setGeometry(QtCore.QRect(10, 290, 211, 20))
        self.search_button.setObjectName(_fromUtf8("search_button"))
        self.searchResult = QtGui.QListView(self.searchBox)
        self.searchResult.setGeometry(QtCore.QRect(250, 20, 411, 291))
        self.searchResult.setObjectName(_fromUtf8("searchResult"))
        self.searchResult.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        ClientInfo.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ClientInfo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ClientInfo.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ClientInfo)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ClientInfo.setStatusBar(self.statusbar)

        self.retranslateUi(ClientInfo)
        QtCore.QMetaObject.connectSlotsByName(ClientInfo)

    def retranslateUi(self, ClientInfo):
        ClientInfo.setWindowTitle(_translate("ClientInfo", "Информация о пациенте", None))
        self.docInfoBox.setTitle(_translate("ClientInfo", "Информация об документе", None))
        self.label_9.setText(_translate("ClientInfo", "Номер", None))
        self.label_7.setText(_translate("ClientInfo", "Тип", None))
        self.label_8.setText(_translate("ClientInfo", "Серия", None))
        self.label_16.setText(_translate("ClientInfo", "Дата выдачи", None))
        self.mainInfoBox.setTitle(_translate("ClientInfo", "Основная информация", None))
        self.label_3.setText(_translate("ClientInfo", "Отчество", None))
        self.label_2.setText(_translate("ClientInfo", "Имя", None))
        self.label.setText(_translate("ClientInfo", "Фамилия", None))
        self.label_4.setText(_translate("ClientInfo", "Пол", None))
        self.label_13.setText(_translate("ClientInfo", "Дата рождения", None))
        self.omcInfoBox.setTitle(_translate("ClientInfo", "Информация об полисе ОМС", None))
        self.label_10.setText(_translate("ClientInfo", "Номер", None))
        self.label_11.setText(_translate("ClientInfo", "Тип", None))
        self.label_12.setText(_translate("ClientInfo", "Серия", None))
        self.label_14.setText(_translate("ClientInfo", "Дата выдачи", None))
        self.label_15.setText(_translate("ClientInfo", "Дата окончания", None))
        self.start_button.setText(_translate("ClientInfo", "Получить информацию", None))
        self.label_6.setText(_translate("ClientInfo", "ID ", None))
        self.searchBox.setTitle(_translate("ClientInfo", "Поиск", None))
        self.label_5.setText(_translate("ClientInfo", "Фамилия", None))
        self.label_17.setText(_translate("ClientInfo", "Имя", None))
        self.label_18.setText(_translate("ClientInfo", "Отчество", None))
        self.label_19.setText(_translate("ClientInfo", "Серия документа", None))
        self.label_20.setText(_translate("ClientInfo", "Номер документа", None))
        self.label_21.setText(_translate("ClientInfo", "Тип документа", None))
        self.label_22.setText(_translate("ClientInfo", "Номер ОМС", None))
        self.label_23.setText(_translate("ClientInfo", "Серия ОМС", None))
        self.label_24.setText(_translate("ClientInfo", "Тип ОМС", None))
        self.search_button.setText(_translate("ClientInfo", "Найти", None))

